// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotCommon.proto

package org.chinalbs.pb;

public final class MotCommon {
  private MotCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StCOMTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.stationharbor.model.StCOMT)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 iYear = 1;</code>
     */
    int getIYear();

    /**
     * <code>optional int32 iMonth = 2;</code>
     */
    int getIMonth();

    /**
     * <code>optional int32 iDay = 3;</code>
     */
    int getIDay();

    /**
     * <code>optional int32 iHour = 4;</code>
     */
    int getIHour();

    /**
     * <code>optional int32 iMin = 5;</code>
     */
    int getIMin();

    /**
     * <code>optional double dSec = 6;</code>
     */
    double getDSec();
  }
  /**
   * Protobuf type {@code org.stationharbor.model.StCOMT}
   */
  public  static final class StCOMT extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.stationharbor.model.StCOMT)
      StCOMTOrBuilder {
    // Use StCOMT.newBuilder() to construct.
    private StCOMT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StCOMT() {
      iYear_ = 0;
      iMonth_ = 0;
      iDay_ = 0;
      iHour_ = 0;
      iMin_ = 0;
      dSec_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StCOMT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              iYear_ = input.readInt32();
              break;
            }
            case 16: {

              iMonth_ = input.readInt32();
              break;
            }
            case 24: {

              iDay_ = input.readInt32();
              break;
            }
            case 32: {

              iHour_ = input.readInt32();
              break;
            }
            case 40: {

              iMin_ = input.readInt32();
              break;
            }
            case 49: {

              dSec_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StCOMT_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StCOMT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chinalbs.pb.MotCommon.StCOMT.class, org.chinalbs.pb.MotCommon.StCOMT.Builder.class);
    }

    public static final int IYEAR_FIELD_NUMBER = 1;
    private int iYear_;
    /**
     * <code>optional int32 iYear = 1;</code>
     */
    public int getIYear() {
      return iYear_;
    }

    public static final int IMONTH_FIELD_NUMBER = 2;
    private int iMonth_;
    /**
     * <code>optional int32 iMonth = 2;</code>
     */
    public int getIMonth() {
      return iMonth_;
    }

    public static final int IDAY_FIELD_NUMBER = 3;
    private int iDay_;
    /**
     * <code>optional int32 iDay = 3;</code>
     */
    public int getIDay() {
      return iDay_;
    }

    public static final int IHOUR_FIELD_NUMBER = 4;
    private int iHour_;
    /**
     * <code>optional int32 iHour = 4;</code>
     */
    public int getIHour() {
      return iHour_;
    }

    public static final int IMIN_FIELD_NUMBER = 5;
    private int iMin_;
    /**
     * <code>optional int32 iMin = 5;</code>
     */
    public int getIMin() {
      return iMin_;
    }

    public static final int DSEC_FIELD_NUMBER = 6;
    private double dSec_;
    /**
     * <code>optional double dSec = 6;</code>
     */
    public double getDSec() {
      return dSec_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iYear_ != 0) {
        output.writeInt32(1, iYear_);
      }
      if (iMonth_ != 0) {
        output.writeInt32(2, iMonth_);
      }
      if (iDay_ != 0) {
        output.writeInt32(3, iDay_);
      }
      if (iHour_ != 0) {
        output.writeInt32(4, iHour_);
      }
      if (iMin_ != 0) {
        output.writeInt32(5, iMin_);
      }
      if (dSec_ != 0D) {
        output.writeDouble(6, dSec_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iYear_);
      }
      if (iMonth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, iMonth_);
      }
      if (iDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, iDay_);
      }
      if (iHour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, iHour_);
      }
      if (iMin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, iMin_);
      }
      if (dSec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, dSec_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chinalbs.pb.MotCommon.StCOMT)) {
        return super.equals(obj);
      }
      org.chinalbs.pb.MotCommon.StCOMT other = (org.chinalbs.pb.MotCommon.StCOMT) obj;

      boolean result = true;
      result = result && (getIYear()
          == other.getIYear());
      result = result && (getIMonth()
          == other.getIMonth());
      result = result && (getIDay()
          == other.getIDay());
      result = result && (getIHour()
          == other.getIHour());
      result = result && (getIMin()
          == other.getIMin());
      result = result && (
          Double.doubleToLongBits(getDSec())
          == Double.doubleToLongBits(
              other.getDSec()));
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IYEAR_FIELD_NUMBER;
      hash = (53 * hash) + getIYear();
      hash = (37 * hash) + IMONTH_FIELD_NUMBER;
      hash = (53 * hash) + getIMonth();
      hash = (37 * hash) + IDAY_FIELD_NUMBER;
      hash = (53 * hash) + getIDay();
      hash = (37 * hash) + IHOUR_FIELD_NUMBER;
      hash = (53 * hash) + getIHour();
      hash = (37 * hash) + IMIN_FIELD_NUMBER;
      hash = (53 * hash) + getIMin();
      hash = (37 * hash) + DSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDSec()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StCOMT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chinalbs.pb.MotCommon.StCOMT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.stationharbor.model.StCOMT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.stationharbor.model.StCOMT)
        org.chinalbs.pb.MotCommon.StCOMTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StCOMT_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StCOMT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chinalbs.pb.MotCommon.StCOMT.class, org.chinalbs.pb.MotCommon.StCOMT.Builder.class);
      }

      // Construct using org.chinalbs.pb.MotCommon.StCOMT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iYear_ = 0;

        iMonth_ = 0;

        iDay_ = 0;

        iHour_ = 0;

        iMin_ = 0;

        dSec_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StCOMT_descriptor;
      }

      public org.chinalbs.pb.MotCommon.StCOMT getDefaultInstanceForType() {
        return org.chinalbs.pb.MotCommon.StCOMT.getDefaultInstance();
      }

      public org.chinalbs.pb.MotCommon.StCOMT build() {
        org.chinalbs.pb.MotCommon.StCOMT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.chinalbs.pb.MotCommon.StCOMT buildPartial() {
        org.chinalbs.pb.MotCommon.StCOMT result = new org.chinalbs.pb.MotCommon.StCOMT(this);
        result.iYear_ = iYear_;
        result.iMonth_ = iMonth_;
        result.iDay_ = iDay_;
        result.iHour_ = iHour_;
        result.iMin_ = iMin_;
        result.dSec_ = dSec_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chinalbs.pb.MotCommon.StCOMT) {
          return mergeFrom((org.chinalbs.pb.MotCommon.StCOMT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chinalbs.pb.MotCommon.StCOMT other) {
        if (other == org.chinalbs.pb.MotCommon.StCOMT.getDefaultInstance()) return this;
        if (other.getIYear() != 0) {
          setIYear(other.getIYear());
        }
        if (other.getIMonth() != 0) {
          setIMonth(other.getIMonth());
        }
        if (other.getIDay() != 0) {
          setIDay(other.getIDay());
        }
        if (other.getIHour() != 0) {
          setIHour(other.getIHour());
        }
        if (other.getIMin() != 0) {
          setIMin(other.getIMin());
        }
        if (other.getDSec() != 0D) {
          setDSec(other.getDSec());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chinalbs.pb.MotCommon.StCOMT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chinalbs.pb.MotCommon.StCOMT) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iYear_ ;
      /**
       * <code>optional int32 iYear = 1;</code>
       */
      public int getIYear() {
        return iYear_;
      }
      /**
       * <code>optional int32 iYear = 1;</code>
       */
      public Builder setIYear(int value) {
        
        iYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iYear = 1;</code>
       */
      public Builder clearIYear() {
        
        iYear_ = 0;
        onChanged();
        return this;
      }

      private int iMonth_ ;
      /**
       * <code>optional int32 iMonth = 2;</code>
       */
      public int getIMonth() {
        return iMonth_;
      }
      /**
       * <code>optional int32 iMonth = 2;</code>
       */
      public Builder setIMonth(int value) {
        
        iMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iMonth = 2;</code>
       */
      public Builder clearIMonth() {
        
        iMonth_ = 0;
        onChanged();
        return this;
      }

      private int iDay_ ;
      /**
       * <code>optional int32 iDay = 3;</code>
       */
      public int getIDay() {
        return iDay_;
      }
      /**
       * <code>optional int32 iDay = 3;</code>
       */
      public Builder setIDay(int value) {
        
        iDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iDay = 3;</code>
       */
      public Builder clearIDay() {
        
        iDay_ = 0;
        onChanged();
        return this;
      }

      private int iHour_ ;
      /**
       * <code>optional int32 iHour = 4;</code>
       */
      public int getIHour() {
        return iHour_;
      }
      /**
       * <code>optional int32 iHour = 4;</code>
       */
      public Builder setIHour(int value) {
        
        iHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iHour = 4;</code>
       */
      public Builder clearIHour() {
        
        iHour_ = 0;
        onChanged();
        return this;
      }

      private int iMin_ ;
      /**
       * <code>optional int32 iMin = 5;</code>
       */
      public int getIMin() {
        return iMin_;
      }
      /**
       * <code>optional int32 iMin = 5;</code>
       */
      public Builder setIMin(int value) {
        
        iMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iMin = 5;</code>
       */
      public Builder clearIMin() {
        
        iMin_ = 0;
        onChanged();
        return this;
      }

      private double dSec_ ;
      /**
       * <code>optional double dSec = 6;</code>
       */
      public double getDSec() {
        return dSec_;
      }
      /**
       * <code>optional double dSec = 6;</code>
       */
      public Builder setDSec(double value) {
        
        dSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double dSec = 6;</code>
       */
      public Builder clearDSec() {
        
        dSec_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.stationharbor.model.StCOMT)
    }

    // @@protoc_insertion_point(class_scope:org.stationharbor.model.StCOMT)
    private static final org.chinalbs.pb.MotCommon.StCOMT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chinalbs.pb.MotCommon.StCOMT();
    }

    public static org.chinalbs.pb.MotCommon.StCOMT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StCOMT>
        PARSER = new com.google.protobuf.AbstractParser<StCOMT>() {
      public StCOMT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StCOMT(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StCOMT> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StCOMT> getParserForType() {
      return PARSER;
    }

    public org.chinalbs.pb.MotCommon.StCOMT getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StGPSTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.stationharbor.model.StGPST)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 iWeek = 1;</code>
     */
    int getIWeek();

    /**
     * <pre>
     *周内秒
     * </pre>
     *
     * <code>optional double dWeekSec = 2;</code>
     */
    double getDWeekSec();

    /**
     * <pre>
     *从起始时刻总秒数
     * </pre>
     *
     * <code>optional double dSecSum = 3;</code>
     */
    double getDSecSum();

    /**
     * <pre>
     *周内天
     * </pre>
     *
     * <code>optional int32 iWeekDay = 4;</code>
     */
    int getIWeekDay();

    /**
     * <code>optional int32 iYear = 5;</code>
     */
    int getIYear();

    /**
     * <code>optional int32 iDoy = 6;</code>
     */
    int getIDoy();

    /**
     * <code>optional double dDaySec = 7;</code>
     */
    double getDDaySec();
  }
  /**
   * <pre>
   *GPS时
   * </pre>
   *
   * Protobuf type {@code org.stationharbor.model.StGPST}
   */
  public  static final class StGPST extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.stationharbor.model.StGPST)
      StGPSTOrBuilder {
    // Use StGPST.newBuilder() to construct.
    private StGPST(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StGPST() {
      iWeek_ = 0;
      dWeekSec_ = 0D;
      dSecSum_ = 0D;
      iWeekDay_ = 0;
      iYear_ = 0;
      iDoy_ = 0;
      dDaySec_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StGPST(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              iWeek_ = input.readInt32();
              break;
            }
            case 17: {

              dWeekSec_ = input.readDouble();
              break;
            }
            case 25: {

              dSecSum_ = input.readDouble();
              break;
            }
            case 32: {

              iWeekDay_ = input.readInt32();
              break;
            }
            case 40: {

              iYear_ = input.readInt32();
              break;
            }
            case 48: {

              iDoy_ = input.readInt32();
              break;
            }
            case 57: {

              dDaySec_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StGPST_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StGPST_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chinalbs.pb.MotCommon.StGPST.class, org.chinalbs.pb.MotCommon.StGPST.Builder.class);
    }

    public static final int IWEEK_FIELD_NUMBER = 1;
    private int iWeek_;
    /**
     * <code>optional int32 iWeek = 1;</code>
     */
    public int getIWeek() {
      return iWeek_;
    }

    public static final int DWEEKSEC_FIELD_NUMBER = 2;
    private double dWeekSec_;
    /**
     * <pre>
     *周内秒
     * </pre>
     *
     * <code>optional double dWeekSec = 2;</code>
     */
    public double getDWeekSec() {
      return dWeekSec_;
    }

    public static final int DSECSUM_FIELD_NUMBER = 3;
    private double dSecSum_;
    /**
     * <pre>
     *从起始时刻总秒数
     * </pre>
     *
     * <code>optional double dSecSum = 3;</code>
     */
    public double getDSecSum() {
      return dSecSum_;
    }

    public static final int IWEEKDAY_FIELD_NUMBER = 4;
    private int iWeekDay_;
    /**
     * <pre>
     *周内天
     * </pre>
     *
     * <code>optional int32 iWeekDay = 4;</code>
     */
    public int getIWeekDay() {
      return iWeekDay_;
    }

    public static final int IYEAR_FIELD_NUMBER = 5;
    private int iYear_;
    /**
     * <code>optional int32 iYear = 5;</code>
     */
    public int getIYear() {
      return iYear_;
    }

    public static final int IDOY_FIELD_NUMBER = 6;
    private int iDoy_;
    /**
     * <code>optional int32 iDoy = 6;</code>
     */
    public int getIDoy() {
      return iDoy_;
    }

    public static final int DDAYSEC_FIELD_NUMBER = 7;
    private double dDaySec_;
    /**
     * <code>optional double dDaySec = 7;</code>
     */
    public double getDDaySec() {
      return dDaySec_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iWeek_ != 0) {
        output.writeInt32(1, iWeek_);
      }
      if (dWeekSec_ != 0D) {
        output.writeDouble(2, dWeekSec_);
      }
      if (dSecSum_ != 0D) {
        output.writeDouble(3, dSecSum_);
      }
      if (iWeekDay_ != 0) {
        output.writeInt32(4, iWeekDay_);
      }
      if (iYear_ != 0) {
        output.writeInt32(5, iYear_);
      }
      if (iDoy_ != 0) {
        output.writeInt32(6, iDoy_);
      }
      if (dDaySec_ != 0D) {
        output.writeDouble(7, dDaySec_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iWeek_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iWeek_);
      }
      if (dWeekSec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, dWeekSec_);
      }
      if (dSecSum_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, dSecSum_);
      }
      if (iWeekDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, iWeekDay_);
      }
      if (iYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, iYear_);
      }
      if (iDoy_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, iDoy_);
      }
      if (dDaySec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, dDaySec_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chinalbs.pb.MotCommon.StGPST)) {
        return super.equals(obj);
      }
      org.chinalbs.pb.MotCommon.StGPST other = (org.chinalbs.pb.MotCommon.StGPST) obj;

      boolean result = true;
      result = result && (getIWeek()
          == other.getIWeek());
      result = result && (
          Double.doubleToLongBits(getDWeekSec())
          == Double.doubleToLongBits(
              other.getDWeekSec()));
      result = result && (
          Double.doubleToLongBits(getDSecSum())
          == Double.doubleToLongBits(
              other.getDSecSum()));
      result = result && (getIWeekDay()
          == other.getIWeekDay());
      result = result && (getIYear()
          == other.getIYear());
      result = result && (getIDoy()
          == other.getIDoy());
      result = result && (
          Double.doubleToLongBits(getDDaySec())
          == Double.doubleToLongBits(
              other.getDDaySec()));
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IWEEK_FIELD_NUMBER;
      hash = (53 * hash) + getIWeek();
      hash = (37 * hash) + DWEEKSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDWeekSec()));
      hash = (37 * hash) + DSECSUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDSecSum()));
      hash = (37 * hash) + IWEEKDAY_FIELD_NUMBER;
      hash = (53 * hash) + getIWeekDay();
      hash = (37 * hash) + IYEAR_FIELD_NUMBER;
      hash = (53 * hash) + getIYear();
      hash = (37 * hash) + IDOY_FIELD_NUMBER;
      hash = (53 * hash) + getIDoy();
      hash = (37 * hash) + DDAYSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDDaySec()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StGPST parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chinalbs.pb.MotCommon.StGPST prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *GPS时
     * </pre>
     *
     * Protobuf type {@code org.stationharbor.model.StGPST}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.stationharbor.model.StGPST)
        org.chinalbs.pb.MotCommon.StGPSTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StGPST_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StGPST_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chinalbs.pb.MotCommon.StGPST.class, org.chinalbs.pb.MotCommon.StGPST.Builder.class);
      }

      // Construct using org.chinalbs.pb.MotCommon.StGPST.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iWeek_ = 0;

        dWeekSec_ = 0D;

        dSecSum_ = 0D;

        iWeekDay_ = 0;

        iYear_ = 0;

        iDoy_ = 0;

        dDaySec_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StGPST_descriptor;
      }

      public org.chinalbs.pb.MotCommon.StGPST getDefaultInstanceForType() {
        return org.chinalbs.pb.MotCommon.StGPST.getDefaultInstance();
      }

      public org.chinalbs.pb.MotCommon.StGPST build() {
        org.chinalbs.pb.MotCommon.StGPST result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.chinalbs.pb.MotCommon.StGPST buildPartial() {
        org.chinalbs.pb.MotCommon.StGPST result = new org.chinalbs.pb.MotCommon.StGPST(this);
        result.iWeek_ = iWeek_;
        result.dWeekSec_ = dWeekSec_;
        result.dSecSum_ = dSecSum_;
        result.iWeekDay_ = iWeekDay_;
        result.iYear_ = iYear_;
        result.iDoy_ = iDoy_;
        result.dDaySec_ = dDaySec_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chinalbs.pb.MotCommon.StGPST) {
          return mergeFrom((org.chinalbs.pb.MotCommon.StGPST)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chinalbs.pb.MotCommon.StGPST other) {
        if (other == org.chinalbs.pb.MotCommon.StGPST.getDefaultInstance()) return this;
        if (other.getIWeek() != 0) {
          setIWeek(other.getIWeek());
        }
        if (other.getDWeekSec() != 0D) {
          setDWeekSec(other.getDWeekSec());
        }
        if (other.getDSecSum() != 0D) {
          setDSecSum(other.getDSecSum());
        }
        if (other.getIWeekDay() != 0) {
          setIWeekDay(other.getIWeekDay());
        }
        if (other.getIYear() != 0) {
          setIYear(other.getIYear());
        }
        if (other.getIDoy() != 0) {
          setIDoy(other.getIDoy());
        }
        if (other.getDDaySec() != 0D) {
          setDDaySec(other.getDDaySec());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chinalbs.pb.MotCommon.StGPST parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chinalbs.pb.MotCommon.StGPST) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iWeek_ ;
      /**
       * <code>optional int32 iWeek = 1;</code>
       */
      public int getIWeek() {
        return iWeek_;
      }
      /**
       * <code>optional int32 iWeek = 1;</code>
       */
      public Builder setIWeek(int value) {
        
        iWeek_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iWeek = 1;</code>
       */
      public Builder clearIWeek() {
        
        iWeek_ = 0;
        onChanged();
        return this;
      }

      private double dWeekSec_ ;
      /**
       * <pre>
       *周内秒
       * </pre>
       *
       * <code>optional double dWeekSec = 2;</code>
       */
      public double getDWeekSec() {
        return dWeekSec_;
      }
      /**
       * <pre>
       *周内秒
       * </pre>
       *
       * <code>optional double dWeekSec = 2;</code>
       */
      public Builder setDWeekSec(double value) {
        
        dWeekSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *周内秒
       * </pre>
       *
       * <code>optional double dWeekSec = 2;</code>
       */
      public Builder clearDWeekSec() {
        
        dWeekSec_ = 0D;
        onChanged();
        return this;
      }

      private double dSecSum_ ;
      /**
       * <pre>
       *从起始时刻总秒数
       * </pre>
       *
       * <code>optional double dSecSum = 3;</code>
       */
      public double getDSecSum() {
        return dSecSum_;
      }
      /**
       * <pre>
       *从起始时刻总秒数
       * </pre>
       *
       * <code>optional double dSecSum = 3;</code>
       */
      public Builder setDSecSum(double value) {
        
        dSecSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *从起始时刻总秒数
       * </pre>
       *
       * <code>optional double dSecSum = 3;</code>
       */
      public Builder clearDSecSum() {
        
        dSecSum_ = 0D;
        onChanged();
        return this;
      }

      private int iWeekDay_ ;
      /**
       * <pre>
       *周内天
       * </pre>
       *
       * <code>optional int32 iWeekDay = 4;</code>
       */
      public int getIWeekDay() {
        return iWeekDay_;
      }
      /**
       * <pre>
       *周内天
       * </pre>
       *
       * <code>optional int32 iWeekDay = 4;</code>
       */
      public Builder setIWeekDay(int value) {
        
        iWeekDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *周内天
       * </pre>
       *
       * <code>optional int32 iWeekDay = 4;</code>
       */
      public Builder clearIWeekDay() {
        
        iWeekDay_ = 0;
        onChanged();
        return this;
      }

      private int iYear_ ;
      /**
       * <code>optional int32 iYear = 5;</code>
       */
      public int getIYear() {
        return iYear_;
      }
      /**
       * <code>optional int32 iYear = 5;</code>
       */
      public Builder setIYear(int value) {
        
        iYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iYear = 5;</code>
       */
      public Builder clearIYear() {
        
        iYear_ = 0;
        onChanged();
        return this;
      }

      private int iDoy_ ;
      /**
       * <code>optional int32 iDoy = 6;</code>
       */
      public int getIDoy() {
        return iDoy_;
      }
      /**
       * <code>optional int32 iDoy = 6;</code>
       */
      public Builder setIDoy(int value) {
        
        iDoy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iDoy = 6;</code>
       */
      public Builder clearIDoy() {
        
        iDoy_ = 0;
        onChanged();
        return this;
      }

      private double dDaySec_ ;
      /**
       * <code>optional double dDaySec = 7;</code>
       */
      public double getDDaySec() {
        return dDaySec_;
      }
      /**
       * <code>optional double dDaySec = 7;</code>
       */
      public Builder setDDaySec(double value) {
        
        dDaySec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double dDaySec = 7;</code>
       */
      public Builder clearDDaySec() {
        
        dDaySec_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.stationharbor.model.StGPST)
    }

    // @@protoc_insertion_point(class_scope:org.stationharbor.model.StGPST)
    private static final org.chinalbs.pb.MotCommon.StGPST DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chinalbs.pb.MotCommon.StGPST();
    }

    public static org.chinalbs.pb.MotCommon.StGPST getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StGPST>
        PARSER = new com.google.protobuf.AbstractParser<StGPST>() {
      public StGPST parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StGPST(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StGPST> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StGPST> getParserForType() {
      return PARSER;
    }

    public org.chinalbs.pb.MotCommon.StGPST getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StBDSTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.stationharbor.model.StBDST)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 iWeek = 1;</code>
     */
    int getIWeek();

    /**
     * <pre>
     *周内秒
     * </pre>
     *
     * <code>optional double dWeekSec = 2;</code>
     */
    double getDWeekSec();

    /**
     * <pre>
     *从起始时刻总秒数
     * </pre>
     *
     * <code>optional double dSecSum = 3;</code>
     */
    double getDSecSum();

    /**
     * <pre>
     *周内天
     * </pre>
     *
     * <code>optional int32 iWeekDay = 4;</code>
     */
    int getIWeekDay();

    /**
     * <code>optional int32 iYear = 5;</code>
     */
    int getIYear();

    /**
     * <code>optional int32 iDoy = 6;</code>
     */
    int getIDoy();

    /**
     * <code>optional double dDaySec = 7;</code>
     */
    double getDDaySec();
  }
  /**
   * <pre>
   *BD时
   * </pre>
   *
   * Protobuf type {@code org.stationharbor.model.StBDST}
   */
  public  static final class StBDST extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.stationharbor.model.StBDST)
      StBDSTOrBuilder {
    // Use StBDST.newBuilder() to construct.
    private StBDST(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StBDST() {
      iWeek_ = 0;
      dWeekSec_ = 0D;
      dSecSum_ = 0D;
      iWeekDay_ = 0;
      iYear_ = 0;
      iDoy_ = 0;
      dDaySec_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StBDST(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              iWeek_ = input.readInt32();
              break;
            }
            case 17: {

              dWeekSec_ = input.readDouble();
              break;
            }
            case 25: {

              dSecSum_ = input.readDouble();
              break;
            }
            case 32: {

              iWeekDay_ = input.readInt32();
              break;
            }
            case 40: {

              iYear_ = input.readInt32();
              break;
            }
            case 48: {

              iDoy_ = input.readInt32();
              break;
            }
            case 57: {

              dDaySec_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StBDST_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StBDST_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chinalbs.pb.MotCommon.StBDST.class, org.chinalbs.pb.MotCommon.StBDST.Builder.class);
    }

    public static final int IWEEK_FIELD_NUMBER = 1;
    private int iWeek_;
    /**
     * <code>optional int32 iWeek = 1;</code>
     */
    public int getIWeek() {
      return iWeek_;
    }

    public static final int DWEEKSEC_FIELD_NUMBER = 2;
    private double dWeekSec_;
    /**
     * <pre>
     *周内秒
     * </pre>
     *
     * <code>optional double dWeekSec = 2;</code>
     */
    public double getDWeekSec() {
      return dWeekSec_;
    }

    public static final int DSECSUM_FIELD_NUMBER = 3;
    private double dSecSum_;
    /**
     * <pre>
     *从起始时刻总秒数
     * </pre>
     *
     * <code>optional double dSecSum = 3;</code>
     */
    public double getDSecSum() {
      return dSecSum_;
    }

    public static final int IWEEKDAY_FIELD_NUMBER = 4;
    private int iWeekDay_;
    /**
     * <pre>
     *周内天
     * </pre>
     *
     * <code>optional int32 iWeekDay = 4;</code>
     */
    public int getIWeekDay() {
      return iWeekDay_;
    }

    public static final int IYEAR_FIELD_NUMBER = 5;
    private int iYear_;
    /**
     * <code>optional int32 iYear = 5;</code>
     */
    public int getIYear() {
      return iYear_;
    }

    public static final int IDOY_FIELD_NUMBER = 6;
    private int iDoy_;
    /**
     * <code>optional int32 iDoy = 6;</code>
     */
    public int getIDoy() {
      return iDoy_;
    }

    public static final int DDAYSEC_FIELD_NUMBER = 7;
    private double dDaySec_;
    /**
     * <code>optional double dDaySec = 7;</code>
     */
    public double getDDaySec() {
      return dDaySec_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (iWeek_ != 0) {
        output.writeInt32(1, iWeek_);
      }
      if (dWeekSec_ != 0D) {
        output.writeDouble(2, dWeekSec_);
      }
      if (dSecSum_ != 0D) {
        output.writeDouble(3, dSecSum_);
      }
      if (iWeekDay_ != 0) {
        output.writeInt32(4, iWeekDay_);
      }
      if (iYear_ != 0) {
        output.writeInt32(5, iYear_);
      }
      if (iDoy_ != 0) {
        output.writeInt32(6, iDoy_);
      }
      if (dDaySec_ != 0D) {
        output.writeDouble(7, dDaySec_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (iWeek_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iWeek_);
      }
      if (dWeekSec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, dWeekSec_);
      }
      if (dSecSum_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, dSecSum_);
      }
      if (iWeekDay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, iWeekDay_);
      }
      if (iYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, iYear_);
      }
      if (iDoy_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, iDoy_);
      }
      if (dDaySec_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, dDaySec_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chinalbs.pb.MotCommon.StBDST)) {
        return super.equals(obj);
      }
      org.chinalbs.pb.MotCommon.StBDST other = (org.chinalbs.pb.MotCommon.StBDST) obj;

      boolean result = true;
      result = result && (getIWeek()
          == other.getIWeek());
      result = result && (
          Double.doubleToLongBits(getDWeekSec())
          == Double.doubleToLongBits(
              other.getDWeekSec()));
      result = result && (
          Double.doubleToLongBits(getDSecSum())
          == Double.doubleToLongBits(
              other.getDSecSum()));
      result = result && (getIWeekDay()
          == other.getIWeekDay());
      result = result && (getIYear()
          == other.getIYear());
      result = result && (getIDoy()
          == other.getIDoy());
      result = result && (
          Double.doubleToLongBits(getDDaySec())
          == Double.doubleToLongBits(
              other.getDDaySec()));
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IWEEK_FIELD_NUMBER;
      hash = (53 * hash) + getIWeek();
      hash = (37 * hash) + DWEEKSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDWeekSec()));
      hash = (37 * hash) + DSECSUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDSecSum()));
      hash = (37 * hash) + IWEEKDAY_FIELD_NUMBER;
      hash = (53 * hash) + getIWeekDay();
      hash = (37 * hash) + IYEAR_FIELD_NUMBER;
      hash = (53 * hash) + getIYear();
      hash = (37 * hash) + IDOY_FIELD_NUMBER;
      hash = (53 * hash) + getIDoy();
      hash = (37 * hash) + DDAYSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDDaySec()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.StBDST parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chinalbs.pb.MotCommon.StBDST prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *BD时
     * </pre>
     *
     * Protobuf type {@code org.stationharbor.model.StBDST}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.stationharbor.model.StBDST)
        org.chinalbs.pb.MotCommon.StBDSTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StBDST_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StBDST_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chinalbs.pb.MotCommon.StBDST.class, org.chinalbs.pb.MotCommon.StBDST.Builder.class);
      }

      // Construct using org.chinalbs.pb.MotCommon.StBDST.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iWeek_ = 0;

        dWeekSec_ = 0D;

        dSecSum_ = 0D;

        iWeekDay_ = 0;

        iYear_ = 0;

        iDoy_ = 0;

        dDaySec_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_StBDST_descriptor;
      }

      public org.chinalbs.pb.MotCommon.StBDST getDefaultInstanceForType() {
        return org.chinalbs.pb.MotCommon.StBDST.getDefaultInstance();
      }

      public org.chinalbs.pb.MotCommon.StBDST build() {
        org.chinalbs.pb.MotCommon.StBDST result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.chinalbs.pb.MotCommon.StBDST buildPartial() {
        org.chinalbs.pb.MotCommon.StBDST result = new org.chinalbs.pb.MotCommon.StBDST(this);
        result.iWeek_ = iWeek_;
        result.dWeekSec_ = dWeekSec_;
        result.dSecSum_ = dSecSum_;
        result.iWeekDay_ = iWeekDay_;
        result.iYear_ = iYear_;
        result.iDoy_ = iDoy_;
        result.dDaySec_ = dDaySec_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chinalbs.pb.MotCommon.StBDST) {
          return mergeFrom((org.chinalbs.pb.MotCommon.StBDST)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chinalbs.pb.MotCommon.StBDST other) {
        if (other == org.chinalbs.pb.MotCommon.StBDST.getDefaultInstance()) return this;
        if (other.getIWeek() != 0) {
          setIWeek(other.getIWeek());
        }
        if (other.getDWeekSec() != 0D) {
          setDWeekSec(other.getDWeekSec());
        }
        if (other.getDSecSum() != 0D) {
          setDSecSum(other.getDSecSum());
        }
        if (other.getIWeekDay() != 0) {
          setIWeekDay(other.getIWeekDay());
        }
        if (other.getIYear() != 0) {
          setIYear(other.getIYear());
        }
        if (other.getIDoy() != 0) {
          setIDoy(other.getIDoy());
        }
        if (other.getDDaySec() != 0D) {
          setDDaySec(other.getDDaySec());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chinalbs.pb.MotCommon.StBDST parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chinalbs.pb.MotCommon.StBDST) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int iWeek_ ;
      /**
       * <code>optional int32 iWeek = 1;</code>
       */
      public int getIWeek() {
        return iWeek_;
      }
      /**
       * <code>optional int32 iWeek = 1;</code>
       */
      public Builder setIWeek(int value) {
        
        iWeek_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iWeek = 1;</code>
       */
      public Builder clearIWeek() {
        
        iWeek_ = 0;
        onChanged();
        return this;
      }

      private double dWeekSec_ ;
      /**
       * <pre>
       *周内秒
       * </pre>
       *
       * <code>optional double dWeekSec = 2;</code>
       */
      public double getDWeekSec() {
        return dWeekSec_;
      }
      /**
       * <pre>
       *周内秒
       * </pre>
       *
       * <code>optional double dWeekSec = 2;</code>
       */
      public Builder setDWeekSec(double value) {
        
        dWeekSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *周内秒
       * </pre>
       *
       * <code>optional double dWeekSec = 2;</code>
       */
      public Builder clearDWeekSec() {
        
        dWeekSec_ = 0D;
        onChanged();
        return this;
      }

      private double dSecSum_ ;
      /**
       * <pre>
       *从起始时刻总秒数
       * </pre>
       *
       * <code>optional double dSecSum = 3;</code>
       */
      public double getDSecSum() {
        return dSecSum_;
      }
      /**
       * <pre>
       *从起始时刻总秒数
       * </pre>
       *
       * <code>optional double dSecSum = 3;</code>
       */
      public Builder setDSecSum(double value) {
        
        dSecSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *从起始时刻总秒数
       * </pre>
       *
       * <code>optional double dSecSum = 3;</code>
       */
      public Builder clearDSecSum() {
        
        dSecSum_ = 0D;
        onChanged();
        return this;
      }

      private int iWeekDay_ ;
      /**
       * <pre>
       *周内天
       * </pre>
       *
       * <code>optional int32 iWeekDay = 4;</code>
       */
      public int getIWeekDay() {
        return iWeekDay_;
      }
      /**
       * <pre>
       *周内天
       * </pre>
       *
       * <code>optional int32 iWeekDay = 4;</code>
       */
      public Builder setIWeekDay(int value) {
        
        iWeekDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *周内天
       * </pre>
       *
       * <code>optional int32 iWeekDay = 4;</code>
       */
      public Builder clearIWeekDay() {
        
        iWeekDay_ = 0;
        onChanged();
        return this;
      }

      private int iYear_ ;
      /**
       * <code>optional int32 iYear = 5;</code>
       */
      public int getIYear() {
        return iYear_;
      }
      /**
       * <code>optional int32 iYear = 5;</code>
       */
      public Builder setIYear(int value) {
        
        iYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iYear = 5;</code>
       */
      public Builder clearIYear() {
        
        iYear_ = 0;
        onChanged();
        return this;
      }

      private int iDoy_ ;
      /**
       * <code>optional int32 iDoy = 6;</code>
       */
      public int getIDoy() {
        return iDoy_;
      }
      /**
       * <code>optional int32 iDoy = 6;</code>
       */
      public Builder setIDoy(int value) {
        
        iDoy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 iDoy = 6;</code>
       */
      public Builder clearIDoy() {
        
        iDoy_ = 0;
        onChanged();
        return this;
      }

      private double dDaySec_ ;
      /**
       * <code>optional double dDaySec = 7;</code>
       */
      public double getDDaySec() {
        return dDaySec_;
      }
      /**
       * <code>optional double dDaySec = 7;</code>
       */
      public Builder setDDaySec(double value) {
        
        dDaySec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double dDaySec = 7;</code>
       */
      public Builder clearDDaySec() {
        
        dDaySec_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.stationharbor.model.StBDST)
    }

    // @@protoc_insertion_point(class_scope:org.stationharbor.model.StBDST)
    private static final org.chinalbs.pb.MotCommon.StBDST DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chinalbs.pb.MotCommon.StBDST();
    }

    public static org.chinalbs.pb.MotCommon.StBDST getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StBDST>
        PARSER = new com.google.protobuf.AbstractParser<StBDST>() {
      public StBDST parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StBDST(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StBDST> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<StBDST> getParserForType() {
      return PARSER;
    }

    public org.chinalbs.pb.MotCommon.StBDST getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MotEphPoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.stationharbor.model.MotEphPo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .google.protobuf.Any object = 1;</code>
     */
    boolean hasObject();
    /**
     * <code>optional .google.protobuf.Any object = 1;</code>
     */
    com.google.protobuf.Any getObject();
    /**
     * <code>optional .google.protobuf.Any object = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getObjectOrBuilder();
  }
  /**
   * Protobuf type {@code org.stationharbor.model.MotEphPo}
   */
  public  static final class MotEphPo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.stationharbor.model.MotEphPo)
      MotEphPoOrBuilder {
    // Use MotEphPo.newBuilder() to construct.
    private MotEphPo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MotEphPo() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MotEphPo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (object_ != null) {
                subBuilder = object_.toBuilder();
              }
              object_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(object_);
                object_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_MotEphPo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_MotEphPo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.chinalbs.pb.MotCommon.MotEphPo.class, org.chinalbs.pb.MotCommon.MotEphPo.Builder.class);
    }

    public static final int OBJECT_FIELD_NUMBER = 1;
    private com.google.protobuf.Any object_;
    /**
     * <code>optional .google.protobuf.Any object = 1;</code>
     */
    public boolean hasObject() {
      return object_ != null;
    }
    /**
     * <code>optional .google.protobuf.Any object = 1;</code>
     */
    public com.google.protobuf.Any getObject() {
      return object_ == null ? com.google.protobuf.Any.getDefaultInstance() : object_;
    }
    /**
     * <code>optional .google.protobuf.Any object = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getObjectOrBuilder() {
      return getObject();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (object_ != null) {
        output.writeMessage(1, getObject());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (object_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getObject());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.chinalbs.pb.MotCommon.MotEphPo)) {
        return super.equals(obj);
      }
      org.chinalbs.pb.MotCommon.MotEphPo other = (org.chinalbs.pb.MotCommon.MotEphPo) obj;

      boolean result = true;
      result = result && (hasObject() == other.hasObject());
      if (hasObject()) {
        result = result && getObject()
            .equals(other.getObject());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasObject()) {
        hash = (37 * hash) + OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + getObject().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.chinalbs.pb.MotCommon.MotEphPo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chinalbs.pb.MotCommon.MotEphPo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.stationharbor.model.MotEphPo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.stationharbor.model.MotEphPo)
        org.chinalbs.pb.MotCommon.MotEphPoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_MotEphPo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_MotEphPo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.chinalbs.pb.MotCommon.MotEphPo.class, org.chinalbs.pb.MotCommon.MotEphPo.Builder.class);
      }

      // Construct using org.chinalbs.pb.MotCommon.MotEphPo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (objectBuilder_ == null) {
          object_ = null;
        } else {
          object_ = null;
          objectBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.chinalbs.pb.MotCommon.internal_static_org_stationharbor_model_MotEphPo_descriptor;
      }

      public org.chinalbs.pb.MotCommon.MotEphPo getDefaultInstanceForType() {
        return org.chinalbs.pb.MotCommon.MotEphPo.getDefaultInstance();
      }

      public org.chinalbs.pb.MotCommon.MotEphPo build() {
        org.chinalbs.pb.MotCommon.MotEphPo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.chinalbs.pb.MotCommon.MotEphPo buildPartial() {
        org.chinalbs.pb.MotCommon.MotEphPo result = new org.chinalbs.pb.MotCommon.MotEphPo(this);
        if (objectBuilder_ == null) {
          result.object_ = object_;
        } else {
          result.object_ = objectBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.chinalbs.pb.MotCommon.MotEphPo) {
          return mergeFrom((org.chinalbs.pb.MotCommon.MotEphPo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.chinalbs.pb.MotCommon.MotEphPo other) {
        if (other == org.chinalbs.pb.MotCommon.MotEphPo.getDefaultInstance()) return this;
        if (other.hasObject()) {
          mergeObject(other.getObject());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.chinalbs.pb.MotCommon.MotEphPo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.chinalbs.pb.MotCommon.MotEphPo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Any object_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> objectBuilder_;
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public boolean hasObject() {
        return objectBuilder_ != null || object_ != null;
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public com.google.protobuf.Any getObject() {
        if (objectBuilder_ == null) {
          return object_ == null ? com.google.protobuf.Any.getDefaultInstance() : object_;
        } else {
          return objectBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public Builder setObject(com.google.protobuf.Any value) {
        if (objectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          object_ = value;
          onChanged();
        } else {
          objectBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public Builder setObject(
          com.google.protobuf.Any.Builder builderForValue) {
        if (objectBuilder_ == null) {
          object_ = builderForValue.build();
          onChanged();
        } else {
          objectBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public Builder mergeObject(com.google.protobuf.Any value) {
        if (objectBuilder_ == null) {
          if (object_ != null) {
            object_ =
              com.google.protobuf.Any.newBuilder(object_).mergeFrom(value).buildPartial();
          } else {
            object_ = value;
          }
          onChanged();
        } else {
          objectBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public Builder clearObject() {
        if (objectBuilder_ == null) {
          object_ = null;
          onChanged();
        } else {
          object_ = null;
          objectBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public com.google.protobuf.Any.Builder getObjectBuilder() {
        
        onChanged();
        return getObjectFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getObjectOrBuilder() {
        if (objectBuilder_ != null) {
          return objectBuilder_.getMessageOrBuilder();
        } else {
          return object_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : object_;
        }
      }
      /**
       * <code>optional .google.protobuf.Any object = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getObjectFieldBuilder() {
        if (objectBuilder_ == null) {
          objectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getObject(),
                  getParentForChildren(),
                  isClean());
          object_ = null;
        }
        return objectBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.stationharbor.model.MotEphPo)
    }

    // @@protoc_insertion_point(class_scope:org.stationharbor.model.MotEphPo)
    private static final org.chinalbs.pb.MotCommon.MotEphPo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.chinalbs.pb.MotCommon.MotEphPo();
    }

    public static org.chinalbs.pb.MotCommon.MotEphPo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MotEphPo>
        PARSER = new com.google.protobuf.AbstractParser<MotEphPo>() {
      public MotEphPo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MotEphPo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MotEphPo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MotEphPo> getParserForType() {
      return PARSER;
    }

    public org.chinalbs.pb.MotCommon.MotEphPo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stationharbor_model_StCOMT_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stationharbor_model_StCOMT_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stationharbor_model_StGPST_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stationharbor_model_StGPST_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stationharbor_model_StBDST_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stationharbor_model_StBDST_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_stationharbor_model_MotEphPo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_stationharbor_model_MotEphPo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017MotCommon.proto\022\027org.stationharbor.mod" +
      "el\032\031google/protobuf/any.proto\"`\n\006StCOMT\022" +
      "\r\n\005iYear\030\001 \001(\005\022\016\n\006iMonth\030\002 \001(\005\022\014\n\004iDay\030\003" +
      " \001(\005\022\r\n\005iHour\030\004 \001(\005\022\014\n\004iMin\030\005 \001(\005\022\014\n\004dSe" +
      "c\030\006 \001(\001\"z\n\006StGPST\022\r\n\005iWeek\030\001 \001(\005\022\020\n\010dWee" +
      "kSec\030\002 \001(\001\022\017\n\007dSecSum\030\003 \001(\001\022\020\n\010iWeekDay\030" +
      "\004 \001(\005\022\r\n\005iYear\030\005 \001(\005\022\014\n\004iDoy\030\006 \001(\005\022\017\n\007dD" +
      "aySec\030\007 \001(\001\"z\n\006StBDST\022\r\n\005iWeek\030\001 \001(\005\022\020\n\010" +
      "dWeekSec\030\002 \001(\001\022\017\n\007dSecSum\030\003 \001(\001\022\020\n\010iWeek" +
      "Day\030\004 \001(\005\022\r\n\005iYear\030\005 \001(\005\022\014\n\004iDoy\030\006 \001(\005\022\017",
      "\n\007dDaySec\030\007 \001(\001\"0\n\010MotEphPo\022$\n\006object\030\001 " +
      "\001(\0132\024.google.protobuf.AnyB\036\n\021org.chinalb" +
      "s.pbB\tMotCommonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_org_stationharbor_model_StCOMT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_stationharbor_model_StCOMT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stationharbor_model_StCOMT_descriptor,
        new String[] { "IYear", "IMonth", "IDay", "IHour", "IMin", "DSec", });
    internal_static_org_stationharbor_model_StGPST_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_stationharbor_model_StGPST_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stationharbor_model_StGPST_descriptor,
        new String[] { "IWeek", "DWeekSec", "DSecSum", "IWeekDay", "IYear", "IDoy", "DDaySec", });
    internal_static_org_stationharbor_model_StBDST_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_stationharbor_model_StBDST_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stationharbor_model_StBDST_descriptor,
        new String[] { "IWeek", "DWeekSec", "DSecSum", "IWeekDay", "IYear", "IDoy", "DDaySec", });
    internal_static_org_stationharbor_model_MotEphPo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_stationharbor_model_MotEphPo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_stationharbor_model_MotEphPo_descriptor,
        new String[] { "Object", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
